### PR TITLE
ExecutorObjectiveC Mods for Swift init method with param(s)

### PR DESCRIPTION
**Pull request by jcaldwell01**
Added a secondary logic check for the probing of Swift init methods
that have one or more params. Fixed warning on Xcode 6.4 for ‘%s’ ->
‘%@‘.

### CODE REVIEW

**Comment by paulstringer** [comment]
Would you be interested in submitting this PR to my fork of cslim?

**Comment by ericmeyer** [comment]
@paulstringer: Apologies for the delay, however the last two pull requests kind of slipped through the cracks. What is your email address? I'd be interested in talking to you about the future of this project. You seem to be the main consumer and certainly the main person opening PRs.

At the very least, I can take a look at the PRs this weekend or early next week.

**Comment by paulstringer** [comment]
Hey @ericmeyer your message must have ended up in Junk as I never received it. Be good to talk, get in touch over at paulstringer at mac dot com

**Comment by ericmeyer** [comment]
@jcaldwell01 Thanks for opening the PR (and apologies for getting to it a year later).

I'm closing this pull request because it is pointed at the wrong branch. Changes for Objective C should be pointed at the cslim branch. Also, in looking at the changes, I was having trouble figuring out exactly how to reproduce the issue in your description. If you are still interested in contributing, development for the project is becoming more active, however I think it would make sense to open a new PR pointed at the correct branch.

**Pull request closed without merging**
