### PR TITLE
Build with cmake + appveyor and travis CI

### PR DESCRIPTION
**Pull request by matlo607**

### CODE REVIEW

**Comment by matlo607** [comment]
Hello @dougbradbury ,
Could you please add the repo in your appveyor account ?

**Comment by dougbradbury** [comment]
@matlo607 : enabled: https://ci.appveyor.com/project/dougbradbury/cslim

**Comment by matlo607** [comment]
@dougbradbury, there is an issue in the configuration of the project.
It's trying to build the master instead of building the branch with `appveyor.yml`
It looks for a visual studio project that does not exist.
Please have a look to https://ci.appveyor.com/project/matlo607/cslim

**Comment by dougbradbury** [comment]
It's set to build all branches... not sure how to kick it off though without another commit to bump it.

**Comment by matlo607** [comment]
I amended the date of the last commit.
The build is on going.

**Comment by matlo607** [comment]
It looks good. You can merge it if you are satisfied after the review.

**Pull request merged**
