### PR TITLE
Build with cmake

### PR DESCRIPTION
**Pull request by dougbradbury**

### CODE REVIEW

**Comment by ldecorps** [comment]
Hello Doug,

I hope you are well.
I am getting my team onto CSlim and so I am starting all over again, from
scratch.

It seems fitnesse is not connecting to my the server. I am using the latest
fitnesse, which has the slim protocol 0.4... Is fitnesse backward
compatible? I remember years ago it's was a finicky business to align the
version of fitness and cslim...

Any help appreciated... btw, where do people go now that the yahoo forum if
down?

Merry Christmas!
Laurent

**Comment by ldecorps** [comment]
HI Dough,

it is all working now. It's just that the port number has to be passed
first as opposed to last (as configured in the example pages).

Cheers,
Laurent

**Comment by dougbradbury** [comment]
Thanks!  Where are the docs wrong?

**Comment by ldecorps** [comment]
Well not really but I found I had to add things like this to force the port
number in first position. This is from the top of my head, I don't have
access to the code I wrote:

!define slim.flag ${${slim.port}}

slim was getting %m (which is defined as the command pattern) instead.
That would cause the slim server to listen on a random port number ... as a
result, there was no connection, causing the test execution to freeze.

Now its all back to normal. If everything goes well, I will have half a
dozen guys writing cpp & java tests through fitnesse.

Let's see how it goes.

Laurent

**Comment by dougbradbury** [comment]
Thanks, Laurent!  Good luck.

**Pull request closed without merging**
